[package]
name = "msglib_v2"
version = "0.0.1"

[addresses]
msglib_v2 = "0x54ad3d30af77b60d939ae356e6606de9a4da67583f02b962d2d3f2e481484e90"

[dependencies]
layerzero_common = { local = "../../layerzero-common" }
msglib_auth = { local = "../msglib-auth" }
zro = { local = "../../zro" }
