[package]
name = "executor_ext"
version = "0.0.1"

[addresses]
executor_ext = "0x54ad3d30af77b60d939ae356e6606de9a4da67583f02b962d2d3f2e481484e90"

[dependencies]
AptosFramework = { local = "../../deps/aptos-core/aptos-move/framework/aptos-framework" }
